version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
     - "3000:3000"
    volumes: 
      - "./app:/src/app"
    environment:
     - NODE_ENV=development
    command: npm run dev
