version: '3.7'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
     - NODE_ENV=development
    ports:
      - 3001:3000
      - 24678:24678
    command: npm run dev
